# Generated by Django 4.2.29 on 2026-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=8),
        ),
    ]
