# Generated by Django 4.2.29 on 2026-03-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordercartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booking_id',
        ),
    ]
