# Generated by Django 4.2.29 on 2026-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
