# Generated by Django 4.2.29 on 2026-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4 recommended)', null=True, upload_to='gallery/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/'),
        ),
    ]
