# Generated by Django 4.2.29 on 2026-04-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_galleryimage_video_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='is_external',
            field=models.BooleanField(default=False, help_text='If checked, images show Shopify/Etsy buttons instead of Book Now/Add to Cart'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='etsy_link',
            field=models.URLField(blank=True, help_text='Etsy product link for this image', null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='shopify_link',
            field=models.URLField(blank=True, help_text='Shopify product link for this image', null=True),
        ),
    ]
