# Generated by Django 4.2.29 on 2026-04-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_gallerycategory_is_external_galleryimage_etsy_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the entire bundle', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='If checked, all images are sold as a bundle at one price'),
        ),
    ]
