# Generated by Django 4.2.29 on 2026-04-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_gallerycategory_bundle_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Prompt Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(upload_to='prompts/%Y/%m/')),
                ('prompt_text', models.TextField(help_text='The actual prompt text — sent to client after payment')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='orders.promptcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
