# Generated by Django 4.2.29 on 2026-04-07 04:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_promptcategory_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_payment_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.prompt')),
            ],
        ),
    ]
