# Generated by Django 4.2.29 on 2026-04-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_promptorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt_file',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, DOC, TXT) — sent to client after payment', null=True, upload_to='prompts/files/%Y/%m/'),
        ),
    ]
