# Generated by Django 4.2.29 on 2026-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_prompt_prompt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text',
            field=models.TextField(blank=True, help_text='The actual prompt text — sent to client after payment'),
        ),
    ]
