# Generated by Django 4.2.29 on 2026-04-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_prompt_prompt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the video (shown in cart and admin)', null=True, upload_to='gallery/thumbnails/%Y/%m/'),
        ),
    ]
