# Generated by Django 4.2.29 on 2026-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_galleryimage_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
